runtime: php74
env_variables:
  INSTANCE_CONNECTION_NAME: master-tangent-340802:asia-southeast2:cloudsqlpds
  DB_USER: postgres
  DB_PASS: qwerty
  DB_NAME: pds-2018

beta_settings:
  cloud_sql_instances: master-tangent-340802:asia-southeast2:cloudsqlpds=tcp:5432